### PR TITLE
Fix build errors.

### PR DESCRIPTION
**Pull request by zogi**
Building as shared=False failed, because OpenEXR needs zlib, which the FindOpenEXR.cmake did not configure.
Also building failed on linux due to wrong library order.

### CODE REVIEW

**Comment by Mikayex** [comment]
Thanks for fixing the build ! I didn't had time to handle the build problems...
By the way, I'm curious about your usage of the package ? Is it another package's dependency or are you simply using it ?

**Comment by zogi** [comment]
It's a common dependency for e.g. OpenImageIO, Alembic, Pixar USD.

**Comment by Mikayex** [comment]
I know, I just wanted to know what was **your** usage of it...

**Comment by zogi** [comment]
Ah, ok. Right now I need it because I'm working with Alembic.

**Pull request merged**
